"""API路由汇总"""
from fastapi import APIRouter

from app.api import auth, schedules, consumes, items, studies, travels, agent, evolution, evolution_advanced, stats, schedule_nlp, scenarios, notifications, nlp, vectors, profile, snapshots, sync, guard, innovation, advanced, fsm, engine, mining, rule_population, memory, team, gepa, stability

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["用户认证"])
api_router.include_router(schedules.router, prefix="/schedules", tags=["时间规划"])
api_router.include_router(consumes.router, prefix="/consumes", tags=["消费记账"])
api_router.include_router(items.router, prefix="/items", tags=["物品收纳"])
api_router.include_router(studies.router, prefix="/studies", tags=["学习督导"])
api_router.include_router(travels.router, prefix="/travels", tags=["出行处理"])
api_router.include_router(agent.router, prefix="/agent", tags=["Agent对话"])
api_router.include_router(evolution.router, prefix="/evolution", tags=["自适应演化"])
api_router.include_router(stats.router, prefix="/stats", tags=["数据统计"])
api_router.include_router(schedule_nlp.router, prefix="/schedule-nlp", tags=["自然语言日程"])
api_router.include_router(scenarios.router, prefix="/scenarios", tags=["跨Agent场景联动"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["消息推送"])
api_router.include_router(nlp.router, prefix="/nlp", tags=["自然语言解析"])
api_router.include_router(vectors.router, prefix="/vectors", tags=["向量存储"])
api_router.include_router(profile.router, prefix="/profile", tags=["用户画像"])
api_router.include_router(snapshots.router, prefix="/snapshots", tags=["演化快照"])
api_router.include_router(sync.router, prefix="/sync", tags=["多设备同步"])
api_router.include_router(guard.router, prefix="/guard", tags=["守护机制"])
api_router.include_router(innovation.router, prefix="/innovation", tags=["核心创新"])
api_router.include_router(advanced.router, prefix="/advanced", tags=["高级智能"])
api_router.include_router(fsm.router, prefix="/fsm", tags=["多Agent协同"])
api_router.include_router(evolution_advanced.router, prefix="/evolution-advanced", tags=["自演化高级机制"])
api_router.include_router(engine.router, prefix="/engine", tags=["底层引擎"])
api_router.include_router(mining.router, prefix="/mining", tags=["数据挖掘层"])
api_router.include_router(rule_population.router, prefix="/rules", tags=["规则体系"])
api_router.include_router(memory.router, prefix="/memory", tags=["记忆与经验"])
api_router.include_router(team.router, prefix="/team", tags=["多Agent协同"])
api_router.include_router(gepa.router, prefix="/gepa", tags=["GEPA Prompt进化"])
api_router.include_router(stability.router, prefix="/stability", tags=["生活稳态维持"])
